#- hosts: all
- hosts: centos
  #sudo: True
  become: yes
  user: centos
  tasks:
    - name: "Atualiza pacotes"
      shell: sudo yum -y update

    - name: "Instalar pre requisitos [NGINX]"
      yum:
        name: epel-release
        state: latest

    # NGINX
    - name: "Instalar [NGINX]"
      yum:
        name: nginx
        state: latest

    # WGET
    - name: "Instalar [WGET]"
      yum:
        name: wget
        state: latest

    # MYSQL
    - name: "Instalar [MYSQL]"
      yum:
        name: mariadb-server
        state: latest

    - name: "Instalando [PHP]"
      yum:
        name: php-fpm
        state: latest

    - name: "Instalando [php-common]"
      yum:
        name: php-common
        state: latest

    - name: "Instalando [php-mysql]"
      yum:
        name: php-mysql
        state: latest

    - name: "Instalando [php-gd]"
      yum:
        name: php-gd
        state: latest

    - name: "Instalando [php-xml]"
      yum:
        name: php-xml
        state: latest

    - name: "Instalando [php-mbstring]"
      yum:
        name: php-mbstring
        state: latest

    - name: "Instalando [php-mcrypt]"
      yum:
        name: php-mcrypt
        state: latest

    - name: Reiniciando Daeler
      service:
        name: daemon_reload

    - name: "Iniciando [Nginx]"
      shell: sudo systemctl start nginx

    - name: "Iniciando [Mysqld]"
      shell: sudo systemctl start mariadb

    - name: "Iniciando [php-fpm]"
      shell: sudo systemctl start php-fpm

    - name: "Criando diretorio caso não exista"
      file:
        path: /var/www/html/blog
        state: directory
        mode: '777'
        recurse: yes

    - name: "Adicionar ao grupo [Wordpress]"
      group:
        name: wordpress

    - name: "Adicionar usuario [Wordpress]"
      user: name=wordpress group=wordpress home=/var/www/html/blog/wordpress/

    - name: "Realizando download [Wordpress]"
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /var/www/html/blog

    - name: "Extrair arquivo [Wordpress]"
      unarchive:
        src: /var/www/html/blog/latest.tar.gz
        dest: /var/www/html/blog
        remote_src: yes
