#- hosts: all
- hosts: centos
  #sudo: True
  user: centos
  tasks:
    - name: "Atualiza pacotes"
      shell: sudo yum -y update

    - name: "Instalar pre requisitos [NGINX]"
      yum:
        name: epel-release
        state: latest

    # NGINX
    - name: "Instalar [NGINX]"
      yum:
        name: nginx
        state: latest

    #- name: "Subindo serviço [NGINX]"
    #  systemd:
    #    name: nginx
    #    state: started



    # WGET
    - name: "Instalar [WGET]"
      yum:
        name: wget
        state: latest

    # MYSQL
    - name: "Instalar [MYSQL]"
      yum:
        name: mysql-server
        state: latest

    - name: "Senha [MYSQL]"
      shell: sudo grep 'temporary password' /var/log/mysqld.log

    - name: "Configurações [MYSQL]"
      systemd:
        name: mysql
        state: started

    - name: "Pre requisitos [WORDPRESS]"
      yum:
        name: php-gd
        state: latest
